name: Run DSM Webhook

on:
  schedule:
     - cron: "*/1 * * * *"  # Runs every 1 minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Execute Webhook Script
        run: |
          chmod +x dsm_webhook.sh
          ./dsm_webhook.sh
